version: '{build}'

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 12

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g grunt-cli
  - yarn

# Don't try to compile the project
build: off

test_script:
  - node --version
  - npm --version
  - yarn test

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules # global npm modules
  - node_modules # local npm modules
