version: "{build}"

clone_depth: 10

# Fix line endings on Windows
init:
    - git config --global core.autocrlf true

environment:
    matrix:
        - nodejs_version: 4
        - nodejs_version: 0.12
        - nodejs_version: 0.10

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install -g grunt-cli
    - npm install

# Don't try to compile the project
build: off

test_script:
    - node --version
    - npm --version
    - npm test

matrix:
    fast_finish: true

cache:
    - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
    - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
    - node_modules -> package.json                                        # local npm modules
